### ISSUE TITLE
dosample fails when uploading split file

### ISSUE THREAD

**Issue by sebastian-nagel** [commoncrawl/webarchive-indexing#1]
Uploading the split file `splits.seq` by [dosample.py](../blob/master/dosample.py) fails with

```
Traceback (most recent call last):
  File "dosample.py", line 31, in <module>
    main()
  File "dosample.py", line 27, in main
    run_sample_job()
  File "dosample.py", line 23, in run_sample_job
    key = job.fs.make_s3_key(job.options.splitfile)
AttributeError: 'SampleCDXJob' object has no attribute 'fs'
```

**Comment by sebastian-nagel** [comment]
Seen in June and July crawl on EMR. Not reproducible on Hadoop / CDH.
